### ISSUE TITLE
ModuleNotFoundError: No module named 'Elastix'

### ISSUE THREAD

**Issue by jamesobutler** [MedicalImageAnalysisTutorials/SlicerCochlea#16]
There are [failing tests](http://slicer.cdash.org/viewTest.php?onlyfailed&buildid=1616867) for the Slicer preview because of an error importing Elastix.

SlicerCochlea is currently not specifying any dependencies when it appears it should be specifying SlicerElastix. The code that needs to be updated is [here](https://github.com/Slicer/ExtensionsIndex/blob/edd1e320e91c3042f91ab1cb9fe198274453b992/SlicerCochlea.s4ext#L15) for **both** the “master” and “4.10” branch of the ExtensionsIndex repo.

See [here](https://github.com/Slicer/ExtensionsIndex/blob/master/SequenceRegistration.s4ext#L15) how the SequenceRegistration extension specified SlicerElastix as a dependency.

**Comment by idhamari** [comment]
Thanks for your comment. I think the problem comes from not updating the extension index. I just sent a new pull request. There is a new VisSimCommon module that depends on Ealstix.

**Comment by jamesobutler** [comment]
With the PR, the failing test is still happening. This issue should remain open.

I have asked a question about the issue which you can be viewed at https://discourse.slicer.org/t/failing-tests-importerror-no-module-named-elastix/7202

**Comment by idhamari** [comment]
Thanks for your effort. All branches are updated! I hope the next build has no failing tests.

**Comment by jcfr** [comment]
Since this is issue has been fixed by https://github.com/lassoan/SlicerElastix/pull/18, I suggest to close this issue.

**Comment by idhamari** [comment]
done!
