### ISSUE TITLE
Simplify code relying on `slicer.modules.<modulename>.path` attribute

### ISSUE THREAD

**Issue by jcfr** [MedicalImageAnalysisTutorials/SlicerCochlea#18]
I suggest to simplify code like the following:

https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/blob/b50284d1a1cb552a7ee38902ded33fd9e5977c6b/VisSimCommon/VisSimCommon.py#L473-L485

to only make use `slicer.modules.<modulename>.path`

**Comment by idhamari** [comment]
Thanks, I will do this after some testing.
