### ISSUE TITLE
Python 2 and 3 compatibility problems

### ISSUE THREAD

**Issue by jamesobutler** [MedicalImageAnalysisTutorials/SlicerCochlea#24]
The code introduced here in the "master" branch is not actually compatible with python 2 and 3.  This code is only python 2 compatible.
https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/blob/063ee637b35c864145f0f2f1f9bb4559b5a7f6d4/VisSimCommon/VisSimCommon.py#L207-L215

**Question:**  Are you wanting one branch to be both python 2 and 3 compatible? Or do you still want to have a "master" and "4.10" branch?

**Comment by idhamari** [comment]
Thanks for reporting! 
It is fixed in the last commit.

To answer your question, I am trying to minimize the code difference, this makes it easier for me for maintenance.

**Comment by jamesobutler** [comment]
Yes, I agree having one branch is easier to maintain. Will you be deleting the “4.10” branch? Also, if you’re going back to using just the “master” branch you will need to update https://github.com/Slicer/ExtensionsIndex/blob/4.10/SlicerCochlea.s4ext#L9
