### ISSUE TITLE
Checksum typos

### ISSUE THREAD

**Issue by jamesobutler** [MedicalImageAnalysisTutorials/SlicerCochlea#25]
https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/commit/063ee637b35c864145f0f2f1f9bb4559b5a7f6d4 introduced typos related to checksums.

https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/blob/063ee637b35c864145f0f2f1f9bb4559b5a7f6d4/CochleaSeg/CochleaSeg.py#L449

`SAH256` should become `SHA256`

**Comment by idhamari** [comment]
Thanks for reporting! 
It is fixed in the last commit.
