### ISSUE TITLE
Problem with Cochlea Segmentation

### ISSUE THREAD

**Issue by Horviratus** [MedicalImageAnalysisTutorials/SlicerCochlea#34]
With Slicer 4.10., the Cochlea Segmentation module always segmented a random cochlea, that is not consist with the image.
The registration module works fine.

![Screenshot_3](https://user-images.githubusercontent.com/46742954/121000067-19f78c00-c78a-11eb-9e26-69e5db52f3de.png)

**Comment by idhamari** [comment]
Sorry, for the late reply! 

For most of the images, I was able to get a pretty good segmentation! sometimes, you should point the location of the cochlea to the center of the cochlea (approximately). 

is it possible to share the image? I will try to check what goes wrong!

In all cases, there will be a major update soon for the code and the model!

**Comment by idhamari** [comment]
close due to no more updates from the user!!!
