### ISSUE TITLE
No result with MacOS and missing sample dataset. 

### ISSUE THREAD

**Issue by young-oct** [MedicalImageAnalysisTutorials/SlicerCochlea#38]
@idhamari I was excited when I found out about this module, and thank you for all your work. I tried to run this module but somehow it's not working. 
OS: MacOS 13.0.1 (22A400)
Slicer Version: 5.2.1

I followed your [youtube tutorial ](https://www.youtube.com/watch?v=jHD3GKepDLs&t=131s) here and I want to mention that the datastore module was also deprecated. I wonder if you can include the dataset in github. 

Error message from the python interpreter.
 Defaults paths: 
      VisSimTools folder: /Users/youngwang/VisSimTools
      Output folder     : /Users/youngwang/VisSimTools/outputs
      elastix binaries are found in /Applications/Slicer.app/Contents/Extensions-31317/SlicerElastix/lib/Slicer-5.2/elastix
      Cochlea Extension is selected
      sha256computedCheckSum: 5a1ec154dbf24404ff7357066b8158642fcbd6f159881e7318e9a11975884824
      Models or contents are wrong, trying to download ...
      Downloading VisSim Tools  ... 
      Downloading VisSimTools others ...
     Extracting to user home 
      Error: can not download and extract VisSimTools ...
[Errno 2] No such file or directory: '/Users/youngwang/VisSimToolsCochlea'
<img width="1512" alt="Screenshot 2022-11-30 at 16 25 40" src="https://user-images.githubusercontent.com/61168470/204901249-9a037918-2322-4a04-81cd-1146d6ea86db.png">
[Errno 2] No such file or directory: '/Users/youngwang/VisSimToolsCochlea'
[VTK] RemoveItem: Failed to find subject hierarchy item by ID 13
[VTK] GetItemName: Failed to find subject hierarchy item by ID 13
[Qt] void qMRMLSubjectHierarchyTreeView::deleteSelectedItems() : Failed to remove subject hierarchy item (ID: 13 , name:  )
[FD] 2022-11-30 16:15:06.177 Slicer[746:7532] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_markedRangeValueWithReply:) block performed very slowly (1.70 secs).
 ..... getting Cochlea location in the input image
Fiducial adding event!
0

**Comment by idhamari** [comment]
One thing you can try: 

move the folder /Users/youngwang/VisSimToolsCochlea/VisSimTools to /Users/youngwang/VisSimTools 

If this does not work, please notice that Mac is not supported so it is better to use it on Windows or Linux.

**Comment by young-oct** [comment]
@idhamari thank you for the wicked quick reply! The tool your group developed is truly awesome. I think the error comes from my dataset(microCT). I got something very nice with the sample dataset I found [here](https://github.com/MedicalImageAnalysisTutorials/VisSimData). If I could make a suggestion, please update the [readme here](https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea). 
![Coclea](https://user-images.githubusercontent.com/61168470/204909627-3c88009e-e9cd-4a2c-8338-8d8927c89f5a.png)

I also validated this with the zeta dataset provided by https://zenodo.org/record/1473724#.Y4fLxezML0o
Once again, great work!

**Comment by idhamari** [comment]
Thanks, I will close this issue.
