### ISSUE TITLE
Use midas sample images for testing

### ISSUE THREAD

**Issue by idhamari** [MedicalImageAnalysisTutorials/SlicerCochlea#8]
the file is created before the download is complete.

try sampledata module:

https://discourse.slicer.org/t/how-to-download-a-file-from-datastore-using-python-script/4964

**Comment by jcfr** [comment]
I suggest to close this issue, use of SampleData has been integrated in https://github.com/MedicalImageAnalysisTutorials/SlicerCochlea/pull/17 and https://github.com/jcfr/SlicerCochlea/tree/fix-CochleaSeg-test

**Comment by idhamari** [comment]
I had a problem with this before. I will try to use the links from Midas again and close this issue if everything is ok.

**Comment by jcfr** [comment]
Since the infrastructure associated the DataStore need to be updated, instead I recommend using the storage from https://cloud.uni-koblenz-landau.de as you are already doing.

**Comment by idhamari** [comment]
Thanks for the info. My plan is to have two alternative links as my account is not permanent.  I will update the links when needed.

**Comment by idhamari** [comment]
In all cases, this issue will be closed this week.

**Comment by jcfr** [comment]
> as my account is not permanent.

I see, an alternative approach would be to create a `MedicalImageAnalysisTutorialsData` project similar to https://github.com/Slicer/SlicerTestingData

**Comment by idhamari** [comment]
Thanks, I will do it.
